export const BAIRROS = ['AEROPORTO',       
    'CABRAL',        
    'CENTRO'            ,
    'FREI SERAFIM'      ,
    'ILHOTAS'           ,
    'MAFUÁ'             ,
    'MARQUÊS'           ,
    'MATADOURO'         ,
    'MATINHA'           ,
    'MORRO DA ESPERANÇA',
    'NOVA BRASÍLIA'     ,
    'PARQUE ALVORADA'   ,
    'PIRAJÁ'            ,
    'PORENQUANTO'       ,
    'PRIMAVERA'         ,
    'SÃO JOAQUIM'       ,
    'VILA OPERÁRIA'     ,
    'ANGÉLICA'          ,
    'ANGELIM'           ,
    'AREIAS'            ,
    'BELA VISTA'        ,
    'BRASILAR'          ,
    'CATARINA'          ,
    'CIDADE NOVA'       ,
    'CRISTO REI'        ,
    'DISTRITO INDUSTRIAL',
    'ESPLANADA'         ,
    'LOURIVAL PARENTE'  ,
    'MACAÚBA'           ,
    'MONTE CASTELO'     ,
    'MORADA NOVA'       ,
    'NOSSA SENHORA DAS GRAÇAS',,
    'PARQUE JACINTA'    ,
    'PARQUE JULIANA'    ,
    'PARQUE PIAUÍ'      ,
    'PARQUE SÃO JOÃO'   ,
    'PARQUE SUL'        ,
    'PEDRA MIÚDA'       ,
    'PIÇARRA'           ,
    'PIO XII'           ,
    'PORTAL DA ALEGRIA' ,
    'PROMORAR'          ,
    'REDENÇÃO'          ,
    'SACI'              ,
    'SANTA CRUZ'        ,
    'SANTA LUZIA'       ,
    'SANTO ANTÔNIO'     ,
    'SÃO LOURENÇO'      ,
    'SÃO PEDRO'         ,
    'TABULETA'          ,
    'TRÊS ANDARES.'     ,
    'TRIUNFO'           ,
    'VERMELHA'          ,
    'ÁRVORES VERDES'    ,
    'CAMPESTRE.'        ,
    'CIDADE JARDIM'     ,
    'FÁTIMA'            ,
    'HORTO'             ,
    'ININGA'            ,
    'JÓQUEI'            ,
    'MORADA DO SOL'     ,
    'MORROS'            ,
    'NOIVOS'            ,
    'NOVO URUGUAI'      ,
    'PEDRA MOLE'        ,
    'PIÇARREIRA'        ,
    'PLANALTO'          ,
    'PORTO DO CENTRO'   ,
    'RECANTO DAS PALMEIRAS',
    'SAMAPI'            ,
    'SANTA ISABEL'      ,
    'SANTA LIA'         ,
    'SÃO CRISTÓVÃO'     ,
    'SÃO JOÃO'          ,
    'SATÉLITE'          ,
    'SOCOPO'            ,
    'TABAJARAS'         ,
    'URUGUAI'           ,
    'VALE DO GAVIÃO'    ,
    'VALE QUEM TEM'     ,
    'VERDE LAR'         ,
    'ZOOBOTÂNICO'       ,
    'BEIRA RIO'         ,
    'BOM PRINCÍPIO'     ,
    'COLORADO'          ,
    'COMPRIDA'          ,
    'EXTREMA'           ,
    'FLOR DO CAMPO'     ,
    'GURUPI'            ,
    'ITARARÉ'           ,
    'LIVRAMENTO'        ,
    'NOVO HORIZONTE'    ,
    'PARQUE IDEAL'      ,
    'PARQUE POTI'       ,
    'REDONDA'           ,
    'RENASCENÇA'        ,
    'SÃO RAIMUNDO'      ,
    'SÃO SEBASTIÃO'     ,
    'TANCREDO NEVES'    ,
    'TODOS OS SANTOS'   ,
    'VERDECAP'          ,
    'ÁGUA MINERAL'      ,
    'ALEGRE'            ,
    'ALTO ALEGRE'       ,
    'AROEIRAS'          ,
    'BOM JESUS'         ,
    'BUENOS AIRES'      ,
    'CHAPADINHA'        ,
    'EMBRAPA'           ,
    'ITAPERU'           ,
    'JACINTA ANDRADE'   ,
    'MAFRENSE'          ,
    'MEMORARE'          ,
    'MOCAMBINHO'        ,
    'MONTE VERDE'       ,
    'OLARIAS'           ,
    'PARQUE BRASIL'     ,
    'POTI VELHO'        ,
    'REAL COPAGRE'      ,
    'SANTA MARIA'       ,
    'SANTA ROSA'        ,
    'VILA SÃO FRANCISCO',
   ]